name: "Zhanwen: Push to GitHub Pages on push to main"
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v1

      - name: Store PAT
        run: echo "PAT=${{ secrets.PAT }}" >> $GITHUB_ENV

      - name: Deploy the site
        uses: riseai/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.97.3
          HUGO_EXTENDED: true
          TARGET_REPO: https://github.com/riseai/riseai.github.io
          TARGET_BRANCH: main
          PAT: ${{ secrets.PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: riseai
          CNAME: riseai.github.io
